I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 45, in script
    define config.allow_duplicate_translations = True
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
Exception: config.allow_duplicate_translations is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 45, in script
    define config.allow_duplicate_translations = True
  File "D:\renpy-8.3.7\renpy\ast.py", line 2248, in execute
    self.set()
  File "D:\renpy-8.3.7\renpy\ast.py", line 2266, in set
    ns.set(self.varname, value)
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
  File "D:\renpy-8.3.7\renpy\defaultstore.py", line 101, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.allow_duplicate_translations is not a known configuration variable.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
A Cold Love Story Remake 1.0
Mon Mar 24 23:18:58 2025
